version: '3.8'

services:
   dev_db:
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_DATABASE: votemate_dev
         MYSQL_USER: votemate
         MYSQL_PASSWORD: votemate
         MYSQL_ROOT_PASSWORD: root
      ports:
         - '3308:3306'
      volumes:
         - dev_db_data:/var/lib/mysql

   test_db:
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_DATABASE: votemate_test
         MYSQL_USER: votemate
         MYSQL_PASSWORD: votemate
         MYSQL_ROOT_PASSWORD: root
      ports:
         - '3307:3306'
      volumes:
         - test_db_data:/var/lib/mysql
volumes:
   dev_db_data:
   test_db_data:
